### ISSUE TITLE
Cipher/decoder error

### ISSUE THREAD

**Issue by aarrwnh** [eagletmt/comic_walker#11]
After some straying, I finally managed to install library on Win10. But now I get errors instead.

> C:/Ruby193/lib/ruby/gems/1.9.1/gems/comic_walker-0.4.0/lib/comic_walker/cipher.rb:31:in `decrypt_b64`: undefined method `unpack` for nil:NilClass (NoMethodError)

**Comment by aarrwnh** [comment]
now I'm getting this error:

> C:/Ruby193/lib/ruby/gems/1.9.1/gems/comic_walker-0.4.0/lib/comic_walker/item_decoder.rb:46:in `from_blob': no decode delegate for this image format`' @ error/blob.c/BlobToImage/364 (Magick::ImageMagickError)

Tried installing library on Ubuntu 12, and I got the same error. Did I forgot to install something else, maybe? I think I all environment variables are set properly.

On win 10 pro 64-bit ver1607:
- ImageMagick 6.7.7-8 2012-06-20 Q8
- ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
- 'identify -list format' now returns empty list for some reason...

**Comment by kavin-90** [comment]
gvim version working superb :smile:

**Comment by AllMelody** [comment]
I also have the issue from the OP. Do you remember how you fixed it

Edit: Never mind, fixed it. Reinstalling from scratch did it for me, for those that find this issue in google.
