### ISSUE TITLE
save command fails

### ISSUE THREAD

**Issue by arisboch** [eagletmt/comic_walker#12]
Here's the error log:

`/var/lib/gems/2.1.0/gems/comic_walker-0.4.0/lib/comic_walker/client.rb:27:in `get_license': 400: Unexpected request parameters (ComicWalker::Client::Error)
        from /var/lib/gems/2.1.0/gems/comic_walker-0.4.0/lib/comic_walker/content_downloader.rb:9:in `save'
        from /var/lib/gems/2.1.0/gems/comic_walker-0.4.0/lib/comic_walker/cli.rb:23:in `block in save'
        from /var/lib/gems/2.1.0/gems/comic_walker-0.4.0/lib/comic_walker/cli.rb:22:in `each'
        from /var/lib/gems/2.1.0/gems/comic_walker-0.4.0/lib/comic_walker/cli.rb:22:in `save'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/2.1.0/gems/comic_walker-0.4.0/bin/comic-walker:4:in `<top (required)>'
        from /usr/local/bin/comic-walker:23:in `load'
        from /usr/local/bin/comic-walker:23:in `<main>'
`

I think they've changed the site layout or something like that.

**Comment by shiarisu** [comment]
Nope, it's a dependency issue.
Here is a quickfix (at least it worked for me):

sudo gem uninstall net-http-persistent
sudo gem uninstall http-cookie
sudo gem install net-http-persistent -v 2.9.4
sudo gem install http-cookie --version 1.0.2

**Comment by arisboch** [comment]
Thank you SO MUCH, it worked!!!!1

**Comment by kavin-90** [comment]
Thanks it works
